### ISSUE TITLE
ns_show=False not working in version 2.0.0

### ISSUE THREAD

**Issue by elide-b** [elide-b/starbars#15]
### Discussed in https://github.com/elide-b/starbars/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **sebjoseph122** October 11, 2024</sup>
Hello, 

First of all thank you for the extremely useful package.

I just installed version 2.0.0 and am having trouble with ns_show. I don't want to show the ns bars, but they are showing even when set to false. </div>

**Comment by elide-b** [comment]
I fixed it already, it was a small oversight on my part, I'm sorry.

Hope you still enjoy it as much! :)

**Comment by sebjoseph122** [comment]
Working well now! Thanks a lot :)
