### ISSUE TITLE
The hue example does not work

### ISSUE THREAD

**Issue by Serena-O** [elide-b/starbars#17]

**Comment by elide-b** [comment]
Hello! Thank you for bringing it to my attention. I'll try to fix it asap :)

**Comment by Serena-O** [comment]
Thanks so much!

**Comment by Serena-O** [comment]
Hello Elide!

I've not been able to automatically have these changes apply to the package
in my jupiter notebook because it still doesn't work, but I see that it
works on your site. How do I automatically get these updates?

Best,
Serena

**Comment by Serena-O** [comment]
Actually, now I have been able to update it. But there are clashes with
version I think. What are the versions of the dependencies? Have you stated
them somewhere? I cannot find it

**Comment by Serena-O** [comment]
Hi Elide!

It works with the latest version of seaborn; It was my seaborn that was
having issues, but thank you so much for the quick fix!!

Best,
Serena
