### ISSUE TITLE
Bars are not plotted at the same level when there are several box plots combined with hues

### ISSUE THREAD

**Issue by AliceJoubert** [elide-b/starbars#20]
Hello !

Thanks for the tool, it's very practical. I have encountered a use case where the annotations behave weirdly. I do not know if you would expect this. 

I am comparing different metrics, so I plot a boxplot for each one next to one another. The twist is, for each metric there was a different processing ("registration" here) so I use `hue` to show that.

Starbars can now handle hues and it technically works, but it will plot the bars each time a little higher : 

```
import seaborn as sns
from starbars import draw_annotation

ax = sns.boxplot(data, x="metric", y="value", hue="registration")

draw_annotation(ax, annotations, bar_gap=0, top_margin=0)
# ex of annotation : (('a', 'DICE'), ('m', 'DICE'), 0.0)
```

![image](https://github.com/user-attachments/assets/6df31948-73c0-4f7f-9f9b-a6203488e8fd)

I am using matplotlib 3.9.2, seaborn 0.13.2 and starbars 3.0.0.

Do you know if that would be easy to fix ? Thanks !

**Comment by elide-b** [comment]
Hi! Unfortunately it's due to how the code has been written. I'll try to find a solution for you asap :)
