### ISSUE TITLE
Compatible with subplots?

### ISSUE THREAD

**Issue by lucindasisk** [elide-b/starbars#4]
Hi there, thanks so much for developing this great package! Is there a way to specify the axis on which the annotation is drawn, for example in the context of Matplotlib subplots? Thank you!!

**Comment by elide-b** [comment]
Hey :)

I have just published a new version that takes into consideration subplots. You'll have to pass an `ax` argument with the coordinates of the plot you want to annotate (such as `starbars.draw_annotation(annotations, ax=axs[1, 0])`). I have also updated the documentation to have an example of such a case.

Hope it helps ✨
