### ISSUE TITLE
Text to bar distance

### ISSUE THREAD

**Issue by Koushouu** [elide-b/starbars#9]
Hi, thanks for this tool, I found it very useful.

Is it possible to add one more input option, which adjusts the distance between the text and the bar?

![Capture](https://github.com/user-attachments/assets/1814afc0-2ee6-473e-93b1-ddebfd1b14db)
Thanks!

**Comment by elide-b** [comment]
Hey! Happy that you like the tool :)

I just fixed and published a new minor version `1.4.0`. The new parameter is called `text_distance` and it's by default set to 1% of the data range (all of the parameters refer to a percentage of the data range).

Always here if you need more help ✨
